language: node_js
node_js:
  - "10" # Current Release
  - "8"  # Active LTS

branches:
  only:
    - development
    - /^greenkeeper/.*$/

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  keep-history: true
  fqdn: scriptdaemon.me
  on:
    branch: development

notifications:
  email: false
